### ISSUE TITLE
나라 상세 페이지 

### ISSUE THREAD

**Issue by HeoJiin** [KimHunJin/Can-We-Go#4]
![스크린샷 2021-12-29 오후 9 25 58](https://user-images.githubusercontent.com/88474655/147662063-234ed3ac-dc95-4bb7-b806-fdc9e9282b5f.png)

1. 타이틀 `detail_name__3EIRL`
`font-weight : 600;` 으로 넣어주세요!

2. 닫기 버튼 `detail_closeButton__1C6gt`이 border z-index보다 낮게 있는듯해욥 올려주세요!

**Comment by KimHunJin** [comment]
닫기버튼은 별도 이슈로 개선하겠습니다!
font-weight 변경완료
