### ISSUE TITLE
필터 페이지

### ISSUE THREAD

**Issue by HeoJiin** [KimHunJin/Can-We-Go#5]
![스크린샷 2021-12-29 오후 9 25 27](https://user-images.githubusercontent.com/88474655/147662445-8d7aca4c-7252-47a4-a484-464bbf3dae02.png)

닫기 버튼 나라상세 페이지와 동일한 버튼으로 바꿔주시면 감사합니다 ! `detail_closeButton__1C6gt`

**Comment by KimHunJin** [comment]
완료
